### ISSUE TITLE
Ausleihbare Exemplar bekommen "nicht ausleihbar" und rote Ampel

### ISSUE THREAD

**Issue by florianruckelshausen** [michaelfreiberg/folio2daia#10]
Ich glaube durch die neuesten Änderungen hat sich die Fallbehandlung so verschoben, dass ausleihbare Items plötzlich als "nicht ausleihbar" und mit roter Ampel angezeigt werden.

https://hds2test.hebis.de/folio/ubgi/Record/HEB442261012 (Einzelexemplar)
https://hds2test.hebis.de/folio/ubgi/Record/HEB452056381 (Mehrfachexemplar)

Die von https://resolver.hebis.de/folioconnector/gi/originalInfo/452056381 gelieferten Informationen sind korrekt, aber der DAIA Konnektor schreibt die Informationen zu "aus_status unbekannt" und "aus_ind g nicht ausleihbar" um.

**Comment by michaelfreiberg** [comment]
Oha! Ich bin erstmal zu einer älteren Version zurückgegangen, damit die Bände wieder ausleihbar erscheinen und schaue mir das Problem jetzt in Ruhe an.

**Comment by michaelfreiberg** [comment]
1bb7876aacb9c8f19f4e3fc0484acf734a0db76e behebt das Problem.
