### ISSUE TITLE
Lizenzpflichtige Elektronische Ressourcen bringen aus_status frei und werden dann nicht proxifiziert

### ISSUE THREAD

**Issue by florianruckelshausen** [michaelfreiberg/folio2daia#2]
Hier kommt noch ein hebis-Ticket und ich kann es gerade nicht selbst überprüfen. Aber in der HDS-Sitzung hatten wir folgenden Fall:

PPN: 516409077 (ist ein lizenzpflichtiges E-Book und muss proxifiziert werden)

Der FOLIO-Konnektor sendet aber aus_status "frei" (wie für eine frei zugängliche Ressource) und damit wird der Link dann nicht proxifiziert. Laut Uwe wäre es am besten, wenn wir da einfach gar keinen aus_status schicken.

**Comment by michaelfreiberg** [comment]
aus_status "frei" wird jetzt nur noch gesendet, wenn ein Lizenzindikator 0 vorliegt.

Er wird wie folgt in den FOLIO-Daten abgelegt:

```xml
<notes>
<holdingsNoteTypeId>d1d99196-8904-4b2e-9125-9f7bbbf54cc1</holdingsNoteTypeId>
<note>0</note>
<staffOnly>true</staffOnly>
</notes>
```

**Comment by florianruckelshausen** [comment]
Alles klar. Das klappt. Ich habe den Zugriff von außerhalb am Smartphone getestet:

Lizenzpflichtiges E-Book PPN 516409077 => Proxy springt in den Link
Freie E-Ressource PPN 511381301 => Linkt geht direkt zur Ressource
