### ISSUE TITLE
Hap-Tabelle hat bei Hap-Namen hinten Anführungszeichen und Komma

### ISSUE THREAD

**Issue by florianruckelshausen** [michaelfreiberg/folio2daia#4]
Werden HAP-Namen ins Standortfeld durchgereicht, sind in HDS2 am Ende immer ein Anführungszeichen und ein Komma zu sehen. Das kommt offenbar aus der hap-tabelle im XSLT und scheint dort systematisch einkodiert zu sein.

Ich könnte es direkt in der Tabellen korrigieren. Aber ich bin mir nicht sicher, ob du hier ein Verfahren verwendest, um die die HAPs von der OPAC-Datei abzugleichen. Falls ja, müsste der Fehler da korrigiert werden. Oder gibt es einen Grund für die beiden Zeichen, den ich vielleicht nicht sehe?

**Comment by michaelfreiberg** [comment]
Habe ich nachgebessert. Die überschüssigen Zeichen sind bei der Überführung der Excel-Liste entstanden.
