### ISSUE TITLE
Abteilungsname und -link bei E-Medien unterdrücken

### ISSUE THREAD

**Issue by florianruckelshausen** [michaelfreiberg/folio2daia#5]
Bei E-Medien geben wir im FOLIO-HDS2-Testsystem im Moment immer Abteilungsname und -link aus. Im HDS2-Produktivsystem machen wir das nicht (weil die VZ die Anzeige von E-Medien zentral steuert und nur bestimmte DAIA-Tags auswertet).

Ich finde die Anzeige ohne Abteilungsname und -link aber bei E-Medien besser. Den Standort bekommen sie ja "nur", weil wir ihn zuweisen müssen. Mein Vorschlag wäre daher, bei den E-Medien-Standorten ILN204/E/E/... das Schicken abt_num, abt_name und abt_link zu unterdrücken. Ich denke, DAIA sollte das trotzdem verarbeiten können.

https://hds2test.hebis.de/folio/ubgi/Record/HEB511381301
https://justfind.hds.hebis.de/Record/HEB511381301

**Comment by michaelfreiberg** [comment]
Nur eine kurze Notiz für mich: Prüfen, ob ein Campus E-Medien eingeführt werden sollte.

**Comment by michaelfreiberg** [comment]
Der Standort sollte nun nicht mehr mitgeliefert werden. Die Campus-Lösung hätte nicht funktioniert, da darüber nur Tags ergänzt und nicht weggelassen werden können. Ich habe daher den XPath-Selector im Fall elektronischer Medien angepasst. Die Infos unter **effectiveLocation** werden nun gar nicht mehr verarbeitet. Änderungen siehe 63d7780
