### ISSUE TITLE
temporaryLoanType wird in FOLIO nicht angezeigt

### ISSUE THREAD

**Issue by florianruckelshausen** [michaelfreiberg/folio2daia#6]
Das Beispiel ist mit beim Übertragen der Banddaten aufgefallen und eigentlich dachte ich, dass wir das schon mal getestet haben. Aber vielleicht täusche ich mich da auch.

Ein Item kann in FOLIO neben dem permanentLoanType auch einen temporaryLoanType haben. Dieser setzt sich dann bei Berechnungen im Ausleihreglement gegenüber dem permanentLoanType durch. Wird er in FOLIO gesetzt sollte er sich auch in HDS2 bei der Anzeige durchsetzen. Das ist aber aktuell nicht der Fall.

Item in FOLIO mit temporaryLoanType "nur für den Lesesaal": https://iln204.k8s-development.hebis-services.de/inventory/view/e322df8d-03d1-49b6-ab6b-02ea5fd41ad9/d1bae563-5ab0-4752-af42-fdc4d9afb683/f2db8542-4d88-410d-a044-f16b5ac7aa9b?filters=staffSuppress.false&qindex=items.barcode&query=10516900&segment=items&sort=title

Die originalinfo enthält den temporaryLoanType: https://resolver.hebis.de/folioconnector/gi/originalInfo/029231566 (in der Mitte beim Item als UUID und ganz unten auch als Text aufgelöst)

Nach DAIA wird er aber nicht durchgereicht und daher auch nicht angezeigt:
https://resolver.hebis.de/folioconnector/gi/objectInfo/029231566
https://hds2test.hebis.de/folio/ubgi/Record/HEB029231566

Sofern also ein temporaryLoanType vergeben ist, sollte er vor dem permanentLoanType in der DAIA-Auswertung berücksichtigt werden.

(Das Beispiel ist aus unseren Migrationsspieldaten und daher ggf. nicht so lange da. Sonst müssen wir uns einfach ein anderes Item passend präparieren.)

**Comment by michaelfreiberg** [comment]
Der temporaryLoanType sollte nun durchgereicht werden.

**Comment by florianruckelshausen** [comment]
Sieht gut aus.
