### ISSUE TITLE
Zeitschriften in Freihandbereich haben Bestelllink

### ISSUE THREAD

**Issue by florianruckelshausen** [michaelfreiberg/folio2daia#8]
Für Zeitschriften in Freihandbereichen schicken wir über DAIA einen aus_link mit, was in HDS folgerichtig zu einem Bestellbutton führt. Der Button ist aber irreführend und muss entfallen.

Geprüft habe ich:
- Es scheint ein Problem zu sein, das Zeitschriften betrifft. Der aus_link kommt nicht bei Monobeständen in Freihandbereichen.
- Das Phänomen tritt abteilungsübergreifend auf. Geprüft habe ich UB und ZRW.
- Die Phänoment tritt nur mit Ausleihindikator i auf? (geschaut habe ich nach Ausind u und g: die sind offenbar nicht betroffen, Ausind i dagegen schon)

Beispiele:
https://hds2test.hebis.de/folio/ubgi/Record/HEB056420773 (Beispiel ZRW)
https://resolver.hebis.de/folioconnector/gi/objectInfo/056420773

https://hds2test.hebis.de/folio/ubgi/Record/HEB047670452 (Beispiel UB, oberes Exemplar)
https://resolver.hebis.de/folioconnector/gi/objectInfo/047670452

**Comment by michaelfreiberg** [comment]
Intellectual Items mit Ausleihindikator i (Fall II in der Tabelle) hatten noch einen Bestelllink, den ich entfernt habe.
