### ISSUE TITLE
Magazin Link fehlt 

### ISSUE THREAD

**Issue by florianruckelshausen** [michaelfreiberg/folio2daia#9]
Ich kann es leider noch nicht genau eingrenzen, aber in bestimmten Fällen fehlt der Linkhinweis aufs Magazin:

Beispiele:
https://hds2test.hebis.de/folio/ubgi/Record/HEB217330525 (beim ausleihbaren Ex ist er da, beim nicht ausleihbaren fehlt er)
https://hds2test.hebis.de/folio/ubgi/Record/HEB047986506

Ich habe zunächst gedacht, es liegt an den Ausleihindikatoren (g, i bei den Beispielen oben), aber bei Monos geht da die Anzeige trotzdem.

https://hds2test.hebis.de/folio/ubgi/Record/HEB518274586 (zweites Ex)

Liegt es daran, dass es ZS sind?

**Comment by michaelfreiberg** [comment]
In den ersten beiden Fällen handelt es um einen Intellectual Item, für die wir den Campus Magazin noch nicht berücksichtigt hatten.

Zu [217330525](https://hds2test.hebis.de/folio/ubgi/Record/HEB217330525): Der Ausleihindikator ist hier g. Sollte es trotzdem einen Link für eine Bestellung in den Lesesaal geben? Dann müssten wir den Fall _Intellectual Item + Ausleihindikator g_ einführen, den es bisher noch nicht gibt, und diesen Fall mit einem Bestelllink ausstatten.

Zu [047986506](https://hds2test.hebis.de/folio/ubgi/Record/HEB047986506): Der Link sollte nun erscheinen.

**Comment by florianruckelshausen** [comment]
> Zu [217330525](https://hds2test.hebis.de/folio/ubgi/Record/HEB217330525): Der Ausleihindikator ist hier g. Sollte es trotzdem einen Link für eine Bestellung in den Lesesaal geben? Dann müssten wir den Fall _Intellectual Item + Ausleihindikator g_ einführen, den es bisher noch nicht gibt, und diesen Fall mit einem Bestelllink ausstatten.

Also der Fall Magazin + Ausind g (nicht ausleihbar) ist im Grunde sinnfrei, kommt aber in der Praxis trotzdem vor. Der OPAC zeigt dann keinen Bestelllink an. Ich würde das so lassen. Ggf. ist das mal ein Notanker, um einen Band von der Benutzung zu sperren.
